-- GRT Nexus Security Database Schema

CREATE DATABASE IF NOT EXISTS GRTSecurityDB;
GO

USE GRTSecurityDB;
GO

CREATE TABLE IF NOT EXISTS users (
  id INT IDENTITY(1,1) PRIMARY KEY,
  name NVARCHAR(150) NOT NULL,
  email NVARCHAR(255) NOT NULL UNIQUE,
  password_hash NVARCHAR(255) NOT NULL,
  role NVARCHAR(50) NOT NULL DEFAULT 'student',
  created_at DATETIME2 DEFAULT SYSUTCDATETIME()
);
GO

CREATE TABLE IF NOT EXISTS devices (
  id INT IDENTITY(1,1) PRIMARY KEY,
  name NVARCHAR(200) NOT NULL,
  ip_address NVARCHAR(50) NOT NULL,
  status NVARCHAR(50) NOT NULL,
  last_seen DATETIME2 DEFAULT SYSUTCDATETIME(),
  metadata NVARCHAR(MAX) NULL
);
GO

CREATE TABLE IF NOT EXISTS alerts (
  id INT IDENTITY(1,1) PRIMARY KEY,
  title NVARCHAR(255) NOT NULL,
  severity NVARCHAR(50) NOT NULL,
  message NVARCHAR(MAX) NOT NULL,
  source NVARCHAR(100) NULL,
  acknowledged BIT DEFAULT 0,
  created_at DATETIME2 DEFAULT SYSUTCDATETIME()
);
GO

CREATE TABLE IF NOT EXISTS notifications (
  id INT IDENTITY(1,1) PRIMARY KEY,
  type NVARCHAR(100) NOT NULL,
  title NVARCHAR(255) NOT NULL,
  message NVARCHAR(MAX) NOT NULL,
  read BIT DEFAULT 0,
  created_at DATETIME2 DEFAULT SYSUTCDATETIME()
);
GO

CREATE TABLE IF NOT EXISTS automation_rules (
  id INT IDENTITY(1,1) PRIMARY KEY,
  name NVARCHAR(200) NOT NULL,
  trigger_type NVARCHAR(100) NOT NULL,
  trigger_config NVARCHAR(MAX) NULL,
  action_type NVARCHAR(100) NOT NULL,
  action_config NVARCHAR(MAX) NULL,
  enabled BIT DEFAULT 1,
  created_at DATETIME2 DEFAULT SYSUTCDATETIME()
);
GO

CREATE TABLE IF NOT EXISTS policies (
  id INT IDENTITY(1,1) PRIMARY KEY,
  title NVARCHAR(255) NOT NULL,
  scope NVARCHAR(150) NOT NULL,
  status NVARCHAR(50) NOT NULL,
  level NVARCHAR(50) NOT NULL,
  priority INT DEFAULT 0,
  created_at DATETIME2 DEFAULT SYSUTCDATETIME()
);
GO
